language: node_js
os: linux
dist: jammy
node_js:
  - "18.16.0"
cache:
  directories:
    - ".meteor"
    - ".babel-cache"
script:
  - travis_retry ./packages/test-in-console/run.sh
env:
  global:
    - CXX=g++-4.8
    - phantom=false
    - PUPPETEER_DOWNLOAD_PATH=~/.npm/chromium
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libnss3

before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu jammy main universe"
  - sudo apt-get update
  - sudo apt-get install -y libnss3
